### ISSUE TITLE
Feature request - EnvironmentVariableOrThrow("MyCoolEnvironmentVariable")

### ISSUE THREAD

**Issue by ghuntley** [cake-build/cake#1033]
I find myself doing the following heaps which is super verbose:

```
var apiKey = EnvironmentVariable("MYGET_API_KEY");
if (string.IsNullOrEmpty(apiKey))
{
    throw new InvalidArgumentException("Could not resolve MyGet API key.");
}
```
Could we please have a method called `EnvironmentVariableOrThrow("MyCoolEnvironmentVariable")` or similar which throws an exception (of your choosing) if environment variable isn't found. Think of it as "bash strict mode".

**Comment by patriksvensson** [comment]
A utility method like this would be a perfect candidate for an addin or just a method declaration in the script.

I'm hesitant to add utility methods like this since there are endless permutations of methods like this (ThrowIfEmpty, FalseIfEmpty, ThrowIfFoo etc). Once added other people would expect similar methods to exist for all different kinds of methods.

Perhaps it would make sense to add a utility method for guard statements like 'Guard.NotNull(variable)'?

@devlead @gep13 Any thoughts about this?

**Comment by devlead** [comment]
A `T NotNull<T>(this T, string message)` would probably be more universally useful.
In that case a static Guard class essentially would be an cake Assert class, maybe CakeAssert makes more sense.

Regardless, agree with @patriksvensson rather see a utility method that work with result type than loads of aliases for each use case.

**Comment by gep13** [comment]
I tend to agree, an addin would be the best place for something like this.

**Comment by gep13** [comment]
@ghuntley going to go ahead and close this, as I don't think this is will end up in Core Cake.  Feel free to re-open if you think there is more to discuss.
