### ISSUE TITLE
Feature request downloadable .cake script directive 

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1053]
I need to use the #load but its not working with esey when i host it with nuget as it needs a path so i created the #nuscript directive.

hope this can get resolved and even added if its all done ok.

**Comment by robgha01** [comment]
i have a fork up and running here https://github.com/robgha01/cake
so far it imports the script like load dose but from a nuget source the only problem is its not installing the  addins tools namespaces etc only the code is imported. see line 132 in ScriptRunner.cs

**Comment by robgha01** [comment]
I have changed the code again removed the hack on NuScriptDirectiveProcessor and solving the problem by adding `public ScriptAnalyzerResult Analyze(FilePath path, out IScriptAnalyzerContext analyzerContext)` in ScriptAnalyzer.cs

Something is still needed to look over as using statement is not working. in the provided zip i added the two cake scripts that i use for testing im using the Test nuget (not mine) to simulate a nuget package with a cake file (copied the cake file manuely into test folder)

with the new method its possible to get a hold of the "IScriptAnalyzerContext" that belong to the script analyzed this way its possible to make micro analyzings, that will merge the code lines from every nuscript directive.

[Debug.zip](https://github.com/cake-build/cake/files/364826/Debug.zip)

**Comment by robgha01** [comment]
@gep13 Here is the code i currently have in dev its tested and working
https://github.com/robgha01/cake/tree/develop

and here is the test files i used https://1drv.ms/u/s!AvOXr9f-QF0pwGl_A-7MsCvFonEo
to test download the dev repo at the above link and unzip the content of the file from onedrive to bin/Debug and start the debuger most of the executable tasks happen in ScriptRunner.cs its there all the magic is located. the processor "#nuscript" only registers every occurance of a tag #nuscript to the NuScripts property in IScriptInformation.cs

**Comment by mholo65** [comment]
Great idea, but shouldn't it be wise to extend the ```#load``` directive instead of creating a new directive? E.g ```#load nuget:?package=MyCustomScripts```

**Comment by robgha01** [comment]
well the load directive is loading files localy by implamenting a new directive we can till use the load directive for local loading scripts in nuget packages if needed ?

**Comment by robgha01** [comment]
Oh yes know i see what you mean, yes that would be much cleaner il see what i can do :)

**Comment by robgha01** [comment]
I updated the PR to extend the #load and #l syntaxes now load directive handles #nuscript directive internaly i had to use the nuscript processor in the load processor as the Process in **UriDirectiveProcessor.cs** line **22** is sealed. and i dide not want to make a copy of the code becuse that would break the dry principes of not repeating code. :) feal free to test the new debug files is here.
https://1drv.ms/u/s!AvOXr9f-QF0pwGl_A-7MsCvFonEo

**Comment by gep13** [comment]
>@mholo65 said...
Great idea, but shouldn't it be wise to extend the #load directive instead of creating a new directive? E.g #load nuget:?package=MyCustomScripts

I agree that an extension to the #load directive might be the best place for this, but we (the Cake Team) are not entirely sure yet whether we want this addition in the Core Cake application.  As a result, there are really a few options....

* Make the changes and directly pull it into Cake Core
* Make the changes and submit them as a Cake Module, which would allow a new pre-processor directive - I would suggest that a name like #loadnuget might make the most sense
* Make changes to Cake Core to allow providers to be added to the #load directive similar to what can be done with the #addin and #tool directives
* Assuming that the above was complete, make the changes as a Module which extended the #load directive with the ability to source the files from a NuGet package.

Ultimately, the best solution would be to do the 3rd and 4th bullet points above.   However, until that work is done, I think the best solution, for now, would be the 2nd bullet point.

Thoughts?

**Comment by robgha01** [comment]
@gep13 i have sucessfully build release in the new brance this 3rd and 4th looks intressting i was thinking on this all the time when i coded the directive, i will keep that in my maind and maybe someting will come out of it :) for now there is some build failures even that the release is building with 0 errors and 0 warnings :/
