### ISSUE TITLE
Default first parameter to cake.exe should be the target, not the script

### ISSUE THREAD

**Issue by garymcleanhall** [cake-build/cake#1187]
### What You Are Seeing?
The default parameter to Cake.exe is the build script.

### What is Expected?
The default parameter should be the target task to run, so we can run 'cake build', 'cake test', just like all other make-likes.

### What version of Cake are you using?
Version 0.15.2+Branch.main.Sha.c2ca4f7ca51c59dc9c47c9830125b4e66cf14e7a

### Are you running on a 32 or 64 bit system?
64 bit.

### What environment are you running on?  Windows? Linux? Mac?
Windows.

### Are you running on a CI Server?  If so, which one?
This is a general issue

**Comment by cpx** [comment]
:+1: 
I would very much like this as well. It would be a breaking change though, for cases where your cakefile is not named build.cake. Perhaps it could be made less breaking by assuming that a first argument ending with ".cake" is the script argument, whereas anything else is assumed to be the target argument?

I'd also personally like if the default file was called "cakefile" instead of "build" but that's maybe not terribly important :wink:

**Comment by garymcleanhall** [comment]
I took a look at how to make this change, but it doesn't look as easy as I'd hoped. The target task - along with all other arguments - is passed through to the script, which is why you need:

```
var target = Argument("target", "Default");  
// ...
RunTarget(target);
```

So, to maintain some level of backward compatibility, the arguments would have to be rewritten up front so that the default positional argument is copied to `target` and the script name (passed via `-s` or `-f` or somesuch) is copied to the default positional argument. 

I've removed `cake.exe` from my path and replaced it with this `cake.cmd` script that does this rewriting for me:

```
call cake.exe cakefile -t=%1
```
