### ISSUE TITLE
NUnit3 using NUnit.ConsoleRunner post v3.2.1 and TeamCity

### ISSUE THREAD

**Issue by danielwertheim** [cake-build/cake#1212]
### What You Are Seeing?
Using v3.2.1 of the NuGet for NUnit.ConsoleRunner and the settings:

```
NoResults = true,
NoHeader = true,
TeamCity = true
```

TeamCity identified and displayed test results. Using v3.4.1 it does not. Not sure if Cake plugin needs to be updated or if it's an NUnit thing.

### What is Expected?
Test results to be identified and reported in TeamCity.

### What version of Cake are you using?
0.15.2

### Are you running on a 32 or 64 bit system?

64

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

TeamCity 9.1.1

### How Did You Get This To Happen? (Steps to Reproduce)

Upgrade from NUnit.ConsoleRunner v3.2.1 to 3.4.1

**Comment by mholo65** [comment]
@danielwertheim did you also install the TeamCity extension for NUnit? As of NUnit 3.4 TeamCity event listener has been separated out of the engine https://github.com/nunit/docs/wiki/Release-Notes

**Comment by mholo65** [comment]
I.e. this package https://www.nuget.org/packages/NUnit.Extension.TeamCityEventListener/

**Comment by danielwertheim** [comment]
@mholo65 no, wasn't aware. `NUnit.Console` says included: https://www.nuget.org/packages/NUnit.Console/

Tried to do:

```
#tool "nuget:?package=NUnit.Extension.TeamCityEventListener"
```

That should work, no?

**Comment by mholo65** [comment]
yep, NUnit.Console includes a lot, in fact its just an empty package which references a bunch of other packages. But since Cake doesn't play nicely with NuGet refernces, you'll have to install the runner (NUnit.ConsoleRunner) + the wanted extensions (e.g. NUnit.Extension.TeamCityEventListener) manually...

**Comment by devlead** [comment]
@danielwertheim it won't work as tool currently expects an exe, though once @patriksvensson is finished with #1202 it'll be configurable.
Your options currently are install via package.config and/or via bootstrapper.

**Comment by mholo65** [comment]
Btw, don't thinl you can install using the ```tool``` directive since Cake requires an exe to be present n the package... Instead you should go for the ```addin``` directive. But make sure that the packages are located in the same directory (e.g. tools/ dir) since NUnit requires that... As a last resort you could go for ```packages.config``` instead of specifying packages in script file (that's what I'm doing)

**Comment by mholo65** [comment]
@devlead missed your comment, but isn't it possible to use addin and have cake install addins to same path as tools? There's a config for that? Writing on phone ( too lazy to check)...

**Comment by devlead** [comment]
You could config the paths, but there's no guarantee it'll work as addin assemblies are loaded by cake.

**Comment by danielwertheim** [comment]
Used packages.config and then it worked with latest versions.
