### ISSUE TITLE
namespace 'Cake.Common.Tools.VSTest' not found on build machine

### ISSUE THREAD

**Issue by fleed** [cake-build/cake#1356]
I'm using the `VSTest` task to run tests and generate `trx` results.
I'm using version `0.17.0` of `cake`.

On my computer, I could set the Logger property using the enumeration value `Cake.Common.Tools.VSTest.VSTestLogger.Trx` and everything works perfectly (but the [documentation](http://cakebuild.net/api/cake.common.tools.vstest/915a0ea9) reports the Logger property as string).

On a build machine (`VSTS build agent`) the same cake script (run using the `cake task for VSTS` returns the error:

`Error: D:/agent/_work/40/s/build.cake(70,26): error CS0234: The type or namespace name 'VSTestLogger' does not exist in the namespace 'Cake.Common.Tools.VSTest' (are you missing an assembly reference?)`

In general, it seems that the behavior of `cake` is not the same on that machine compared to mine. Besides the operating system (Windows 7 on build, 10 on my dev computer) they're almost equivalent for installed software.

What could be the problem?

**Comment by gep13** [comment]
If you check the release notes for Cake 0.17.0 https://github.com/cake-build/cake/releases/tag/v0.17.0 you will see that there was a breaking change in this area.

It sounds to me like your build machine is correctly using 0.17.0 of Cake, while locally you are still using an older version.

To verify this, go into your local tools.folder in the repo, then Cake. Right click on the Cake.exe and look at it properties to find the version number. I suspect this will be 0.16.2, or similar.

If this is the case, delete the cake folder in tools, and then re-run your build.

Have you committed the packages.confit file into your repo in order to pin usage to a specific version of cake? If not, this is highly recommended.

**Comment by fleed** [comment]
hi @gep13 
I've found the [breaking change](https://github.com/cake-build/cake/pull/1143). Deleting the tools directory and running the script again fixed it.
I will commit the `packages.config` file as you suggested, thank you!
