### ISSUE TITLE
Spaces in #load path will cause an Illegal characters in path error.

### ISSUE THREAD

**Issue by WayneHiller** [cake-build/cake#1389]
If a space is included in the path to the #load directive such as #load "../folder with space/test.cake" an error "Illegal characters in path" will be generated. 

It seems the load directive processing is splitting the line by spaces, regardless if it's quoted or not.

**Comment by agc93** [comment]
Caused by the `tokens[1].UnQuote()` call in [this line](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Scripting/Processors/LoadDirectiveProcessor.cs#L40) of the `LoadDirectiveProcessor`.

Seems to me like changing that line to a `string.Join(' ', tokens.ToList().Skip(1)).UnQuote()` (as messy as that seems) should resolve this.

Thoughts @patriksvensson ? I'm happy to throw together a PR for this if you don't think that will break too much else..

**Comment by phillipsj** [comment]
So i just ran into this error after upgrading to Cake 0.17 for my build.  But it inst' realated to the load directive.

**Comment by agc93** [comment]
@phillipsj What is it related to then? I haven't retested @WayneHiller's actual problem since the updates to the load directive (to support custom schemes) came in.

**Comment by patriksvensson** [comment]
@agc93 I have no objection to you creating a PR for this 😄

**Comment by WayneHiller** [comment]
Have you located what line in your script is causing the error?

**Comment by phillipsj** [comment]
It is being thrown by an Addin.

**Comment by WayneHiller** [comment]
I just tested putting a space in the #load path and the error still occurs in version 0.17

**Comment by patriksvensson** [comment]
Yes. We will need to fix this for 0.18.

**Comment by agc93** [comment]
@phillipsj I suspect it is a different error then, as I doubt an addin will be affected by changes in the `#load` directive's logic. Could be wrong though.

@patriksvensson @WayneHiller I will try and get a chance to have a look at this today or tomorrow.
