### ISSUE TITLE
Arguments missing for Octopus Deploy tool

### ISSUE THREAD

**Issue by islopma** [cake-build/cake#1587]
Octopus Deploy provides the tool Octo.exe, which is integrated into Cake under the **Cake.Common.Tools.OctopusDeploy** namespace. One feature that the tool provides is to deploy the latest release from a selected channel (using options _--channel "Beta" --version latest_).

The thing is that not every option is currently available through Cake, such as the _channel_ option, so one has to resort to invoking Octo.exe directly. It would be nice if this option, and maybe others, could be added to OctopusDeployReleaseDeploymentSettings.

**Comment by mholo65** [comment]
@islopma 
> so one has to resort to invoking Octo.exe directly.

Instead of resorting to calling `Octo.exe` directly you could always use [ArgumentCustomization](http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8) on `OctopusDeployReleaseDeploymentSettings` as a workaround.

That said. Are you in a position to submit a PR for adding `Channel` and `Version`/`ReleaseNumber` to `OctopusDeployReleaseDeploymentSettings`?

**Comment by islopma** [comment]
That's a nice workaround. I will test it and if it works I will be submitting a PR with the `Channel` option.

**Comment by devlead** [comment]
Fixed by #1590
