### ISSUE TITLE
Include more detailed exception information when Exception is AggregateException

### ISSUE THREAD

**Issue by richardgavel** [cake-build/cake#2087]
I have Tasks that will execute a Parallel.Invoke of an array of Actions. However, when an error happens, all I'll see is the "One or more errors occured". Maybe AggregateExceptions should output the message of each child exception.

**Comment by devlead** [comment]
Which version on Cake are you using, have you tried executing Cake with [diagnostic verbosity](https://stackoverflow.com/questions/38658660/how-to-enable-diagnostic-verbosity-for-cake)?

**Comment by jnm2** [comment]
If changing the verbosity affects it, I would wonder is it ever helpful to see only the message in the special case of an AggregateException?

**Comment by devlead** [comment]
@jnm2 Issue could be that it's already within an aggregate exception because the async support. So could be an extra layer of abstraction. Whereas diagnostic gives the whole stack trace.

**Comment by jnm2** [comment]
@devlead It is an extra layer of abstraction because he is using `Parallel.Invoke`. I ran into the same thing with `Task.WhenAll`. It's sort of like if I wrote `throw new AggregateException(new InvalidOperationException("foo"))`. I could be wrong, but wouldn't it be nice if Cake showed the messages of the InnerExceptions collection even when I'm on the default verbosity and not looking for the stack trace?

**Comment by devlead** [comment]
Well anything's possible would need to be recursive then I guess. to fetch inner inner exception messages and so on too.

**Comment by jnm2** [comment]
Yes, that's a good idea! it would be like Visual Studio's exception helper window!

```cs
throw new AggregateException(
    new AggregateException(
        new InvalidOperationException("hello")));
```

Makes it show:

![image](https://user-images.githubusercontent.com/8040367/37523783-599c2c86-28fe-11e8-8b84-0d6fa10b8d0a.png)

And here's the middle one:

![image](https://user-images.githubusercontent.com/8040367/37523826-79877262-28fe-11e8-9096-399664a4a434.png)

**Comment by patriksvensson** [comment]
I wonder if Ben Adams magic exception demystifier exists as a source package... 😄

**Comment by Duracell1989** [comment]
Some issue here;
I do multiple validations and combine them in 1 AggregateException.
I don't want the users to: fix 1 validation; re-run; new error; fix; re-run; etc.
That's why I want to combine them in 1 AggregateException and then I just need to throw 1 exception with all the relevant information.

**Comment by tlecomte** [comment]
Given that the code already tries to handle `AggregateException` [here](https://github.com/cake-build/cake/blob/5fd2df772113e6ef9b9d77507d3becb48e1b4e40/src/Cake/Program.cs#L100), could it be that we are just missing support for _nested_ `AggregateException`s ? Looks like it can be handled with [`AggregateException.Flatten`](https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception.flatten?view=netframework-4.7.2).
