### ISSUE TITLE
NuGetRestore with MSBuild 15.7.x fails

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake#2202]
### What You Are Seeing?
`NuGetRestore` falls back to MSBuild 4.0 when the latest Visual Studio BuildTools 2017 (15.7.x) are installed).
I always get:
`MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.`

I even tried:
```
NuGetRestore(solutionFile, new NuGetRestoreSettings() {
    Verbosity = NuGetVerbosity.Detailed,
    ArgumentCustomization = args => args.Append("-MSBuildVersion 15.7")
});
```
but then I get:
```
NuGet Version: 4.6.2.5055
Cannot find the specified version of msbuild: '15.7'
```

My current workaround is to use:
```
MSBuild(solutionFile, new MSBuildSettings {
    Verbosity = Verbosity.Minimal,
    ToolVersion = MSBuildToolVersion.VS2017,
    Configuration = configuration,
}.WithTarget("restore"));
```

### What is Expected?
The correct MSBuild should be used

### What version of Cake are you using?
0.28.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Yes, but reproducible locally.

**Comment by devlead** [comment]
Checking docs for NuGet command line ( https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore )


MSBuildVersion | (3.2+) Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14, 15. By default the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
-- | --

15,7 doesn't seem to be an valid option for that tool.

**Comment by patriksvensson** [comment]
Looks like a problem with NuGet and not Cake. Closing this for now. Feel free to reopen if you think this has been done in error.
