### ISSUE TITLE
Built framework for .NET Core should be NETCoreApp not NETStandard

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#2303]
I'd say [this](https://github.com/cake-build/cake/blob/9dd24e46aee8cf38a425f184b447ee00820bece8/src/Cake.Core/Polyfill/EnvironmentHelper.cs#L122) should be `NETCoreApp,Version=2.1`

**Comment by adamhathcock** [comment]
Ah, yes.  This goes back to issues I had.

All entrypoints should target a runtime but shared DLLs should be a standard.

The problem is resolving what the build target is of the current assembly when executing on all the different runtimes.  The build target could be a standard or a runtime but it's not consistent in some way.  Hopefully, you can correct my mistake :)

**Comment by mholo65** [comment]
Fixed in https://github.com/cake-build/cake/pull/2604
