### ISSUE TITLE
There's no way to set platform like Debug|iPhone

### ISSUE THREAD

**Issue by jessejiang0214** [cake-build/cake#2314]
### What You Are Seeing?
I trying to build the solution with iPhone platform, as the depending library only build with ARM not x86
### What is Expected?
I want to call MSBuild setting like this ```.SetPlatformTarget("iPhone")```

### What version of Cake are you using?
0.30.0
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Mac
### How Did You Get This To Happen? (Steps to Reproduce)

[Check this line](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs#L240) 
The platform should not be an enum, it should be a string. As in future, maybe more platform add.

**Comment by devlead** [comment]
Isn't `Debug|iPhone` a configuration, if so that's set using the [SetConfiguration(MSBuildSettings, string)](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildSettingsExtensions/8B9CC638) method.

**Comment by gigi81** [comment]
I have the same issue. Just to clarify:
"Debug" is the configuration
"iPhone" (or whatever, it can be any arbitrary name) is the platform.

I have this workaround for the moment to make it work:

```
        MSBuild(solutionPath, settings =>
        {
            settings.SetConfiguration("Debug");
                    
            settings.ArgumentCustomization = args => args.Append("/p:platform=\"iPhone\"");
        });
```

The problem is that [SetPlatformTarget ](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildSettingsExtensions/D9A56C8C) does not allow to set a custom platform but only default ones
