### ISSUE TITLE
Unable to load transitive dependency for cake addin

### ISSUE THREAD

**Issue by Insire** [cake-build/cake#2336]
As discussed with Gary on gitter, here the issue report to my problem, which looks like this:

### What You Are Seeing?

I have a cake addin targeting cake 0.30.0 that relies on a private .net standard 2.0 library that i have written and compiled, which in turn relies on ClosedXML 0.93.1.

When running a cake script using my addin, it fails when trying to load that addin, telling me it can't find the file, even though its physically available in the ``tools/Addins/`` folder.

### What is Expected?
That i can run my cake script without setting ``UseInProcessClient`` to true, since that doesnt support loading packages from a private NuGet feed (yet).

### What version of Cake are you using?
0.30.0

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
nope

### How Did You Get This To Happen? (Steps to Reproduce)
- download [Reproduction.zip](https://github.com/cake-build/cake/files/2506580/Reproduction.zip)
- extract it
- run the build.ps1 file in ``.\Reproduction\StandardLibrary``
- [EDIT] you might have to alter the path to the local nuget feed from build.cake file in ``.\Reproduction\StandardLibrary`` to a folder that exists on your system
- run the actual build.ps1 file in ``.\Reproduction\CakeScript``

### Output Log
[german build.log with fusion.log enabled](https://github.com/cake-build/cake/files/2506593/build.log)

**Comment by mholo65** [comment]
@Insire `build.cake` in `.\Reproduction\Cakescript\` has the following addin directive:
```
#addin "nuget:?package=StandardLibrary&version=0.0.1.0"
```

In order to load dependencies, you must add `loaddependencies=true`, like this:
```
#addin "nuget:?package=StandardLibrary&version=0.0.1.0&loaddependencies=true"
```

This is however only possible with the in-process NuGet Client. You however say:
> run my cake script without setting UseInProcessClient to true, since that doesnt support loading packages from a private NuGet feed (yet).

I would however say that in-process NuGet client supports private feeds, you'd however need to add the feed to a `NuGet.Config` file (use either `apikey` or `packageSourceCredentials` as specified [here](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections)) and place it in your root. NOTE! DO NOT specify the feed in your `#addin` directive (there's a known issue where credentials won't be picked up if feed is specified in the directive).

Another way, that doesn't include `loaddependencies` or in-process NuGet client is to specify all the dependencies (in correct order) as `#addin` directives. In your case that would look something like:
```
#addin "nuget:?package=System.IO.Packaging&version=4.0.0"
#addin "nuget:?package=System.IO.FileSystem.Primitives&version=4.0.1"
#addin "nuget:?package=FastMember.Signed&version=1.3.0"
#addin "nuget:?package=ExcelNumberFormat&version=1.0.3"
#addin "nuget:?package=DocumentFormat.OpenXml&version=2.7.2"
#addin "nuget:?package=ClosedXML&version=0.93.1"
#addin "nuget:?package=StandardLibrary&version=0.0.1.0"
```

Please let me know if any of the above solved the problems you were seeing. Thanks!

**Comment by Insire** [comment]
Thanks for your insight, will report back on this later.

**Comment by Insire** [comment]
Allright, i tried adding the dependencies of ClosedXML and ClosedXML itself explicitly as addin to the cake script and that worked as described. Thanks for your help!
