### ISSUE TITLE
NUnit3Settings should support TestParam

### ISSUE THREAD

**Issue by twenzel** [cake-build/cake#2654]
### What You Are Seeing?
I see a warning `--params is deprecated and will be removed in a future release. Please use --testparam instead.' when using NUnit.ConsoleRunner 3.10.0 and using the `Params` property of the NUnit3Settings class.

### What is Expected?
Either redirect the values from `Params` to the `--testparam` parameter or provide a dedicated `TestParams` property.

### What version of Cake are you using?
0.33

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Execute Nunit3 unit tests with parameters

### Output Log
```
Executing: C:\xyz\tools\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe
--params is deprecated and will be removed in a future release. Please use --testparam instead.
```

**Comment by joshuacookdev** [comment]
I glanced over this one last night, and it seems like there is more than just a difference between the flag names - namely the way the string is delimited in commands. (I think) the only way to keep this from being a breaking change in existing Cake scripts is to _leave support in place for the --params flag, and add support for the --testparam flag_ (rather than converting it behind the scenes). IMO, this would both add support for the new flag, and encourage users to convert their cake scripts to the new flag moving forward.

A Brief writeup on the different flags [from NUnit docs](https://docs.nunit.org/articles/nunit/running-tests/Console-Command-Line.html)
* --testparam:PARAMETER, --tp:PARAMETER | 
  * A test PARAMETER specified in the form NAME=VALUE for consumption by tests. Multiple parameters must be specified separated using a --testparam or --tp option for each.
* --params=PARAMETER, --p=PARAMETER | (NOTE: this is deprecated and will be removed in a future release. Please use --testparam instead.) 
  * A test PARAMETER specified in the form NAME=VALUE for consumption by tests. Multiple parameters may be specified, separated by semicolons or by repeating the --params option multiple times. Case-sensitive.


@augustoproiete - Any thoughts on supporting both, and also on implementation for the multiple --testparam flags as the delimiter? I don't know off-hand of other examples in Cake that use multiple flags for delimiting but can take some time after work today to explore for examples already in the source.

**Comment by joshuacookdev** [comment]
So I poked around briefly on the issue, and had a question on the teams preferred implemenation:

In the [NUnit Command Line Options documentation](https://docs.nunit.org/articles/nunit/running-tests/Console-Command-Line.html), they describe the difference between the two options like so:

--testparam:PARAMETER, --tp:PARAMETER | A test PARAMETER specified in the form NAME=VALUE for consumption by tests. Multiple parameters must be specified separated using a --testparam or --tp option for each.
-- | --
--params=PARAMETER, --p=PARAMETER | (NOTE: this is deprecated and will be removed in a future release. Please use --testparam instead.) A test PARAMETER specified in the form NAME=VALUE for consumption by tests. Multiple parameters may be specified, separated by semicolons or by repeating the --params option multiple times. Case-sensitive.

This leads to my two question: Do we want to support both options (i.e. a TestParam and a Param property), or do we want to convert Params to TestParam behind the scenes? The differences being how multiple parameters are delimited (which shouldn't impact Cake) and `=` vs `:` are both easily handled in NUnit3Runner.cs, if we decide to move forward with the conversion.

My gut says adding TestParam and supporting both is the safest way to move forward as it supports NUnit < v3.10, but I figured I'd ask. Thoughts on the matter, @augustoproiete?
