### ISSUE TITLE
No one monitoring cake-vso repo?

### ISSUE THREAD

**Issue by richardgavel** [cake-build/cake#2723]
I submitted an update for the Cake task for Azure DevOps, as it is warning about referencing a component that is being deprecated, but no one seems to be monitoring that repo?

**Comment by gep13** [comment]
@richardgavel am I right in saying that you are referring to this one:

https://github.com/cake-build/cake-vso/pull/49

The repository is being monitored, we the @cake-build/cake-team monitor all our repositories, and have integrations for notifications whenever things are asked/raised, etc, however, it does come down to priorities, and unfortunately, that repository hasn't been prioritised.  I am currently travelling for work, which means I should have a little extra time in my evenings since I won't have the usual things that occupy my time, so I am going to try to take a look at that repository tomorrow evening, and see if I can get it looked at and merged.

For now, I am going to go ahead and close out this issue.
