### ISSUE TITLE
Enable AnsiConsoleRenderer in TeamCity and Azure Pipelines

### ISSUE THREAD

**Issue by KatoStoelen** [cake-build/cake#2966]
I see that AnsiConsoleRenderer is enabled for GitHub Actions (and terminals that supports it).

Since both TeamCity (since 9.1) and Azure Pipelines now supports ANSI coloring, it would make the world much more colorful if AnsiConsoleRenderer is enabled for those build systems as well.

**Comment by augustoproiete** [comment]
@KatoStoelen I've opened PRs to enable the `AnsiConsoleRenderer` for Azure Pipelines (#2968) and TeamCity (#2969).

In the meantime (as a workaround) if you want to enable colors _today_, you can "cheat" by setting an environment variable that will tell Cake that ANSI is supported:

- If your builds **are** running on Windows, set an environment variable `ConEmuANSI` with the value `On`
- If your builds are **not** running on Windows, set an environment variable `TERM` with the value `ansi`

This works for any CI system, including TeamCity and Azure Pipelines.

---

Just be aware that the colors on TeamCity don't look as nice as you'd expect because Cake is sets a black background color on the messages, which are displayed on a white background in TeamCity if you're using the default theme.

![image](https://user-images.githubusercontent.com/177608/101235993-9d350980-36a3-11eb-9d9f-ba0901e86474.png)

---

Also, some messages such as the summary report at the end of the build (with green forecolor on a regular console) are not emitting ANSI color codes and instead are using `Console.ForegroundColor` thus they won't have colors even with the `AnsiConsoleRenderer` enabled.

**Comment by KatoStoelen** [comment]
Thanks, @augustoproiete!

Went looking for ways to customize `ConsolePalette`, but did not find any (apart from using Cake.Frosting and a custom `IConsole`). Hence, I started to think that it might be better to make this an opt-in feature. Either that, or make ConsolePalette customizable, or add some `BuildSystem` specific palettes (might cause issues for people using custom themes).

I guess with your current PRs, there is no way to opt-out of ANSI coloring?

**Comment by augustoproiete** [comment]
@KatoStoelen Yes, as you probably noticed the [colors are all hard-coded in AnsiConsoleRenderer.](https://github.com/cake-build/cake/blob/4214b5201ccb35f76b49ae77eb7180875006282f/src/Cake.Core/Diagnostics/Console/AnsiConsoleRenderer.cs#L25-L63) at the moment, so supporting custom color palettes would be a new feature to be added.

Cake also doesn't have a way of opting out of ANSI coloring and it would be another new feature to be added. On this one it might make sense to follow the https://no-color.org standard that a number of other CLI systems use.

**Comment by KatoStoelen** [comment]
I'll add new feature requests for both (customizable palette and opt-out of ANSI coloring).

The opt-out feature might be a great addition to this feature, since enabling ANSI coloring in TeamCity, where most people (I'm assuming) have a white background, would be somewhat intrusive.

Customizable palette would also be great, but I understand that this one might require more effort.
