### ISSUE TITLE
Add alias for dotnet workload install command

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3481]
`dotnet workload install` - Installs optional workloads. Introduced with .NET 6 SDK.

The `dotnet workload install` command installs one or more optional workloads. Optional workloads can be installed on top of the .NET SDK to provide support for various application types, such as .NET MAUI and Blazor WebAssembly AOT.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install

**Comment by Marusyk** [comment]
Please assign it to me

**Comment by Marusyk** [comment]
Hi @pascalberger @augustoproiete 
could you please create a separate issue to add integration tests for all workload aliases to https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake?

It'd be better to add tests when all aliases will be merged because for instance  `dotnet workload uninstall`  - there is nothing to uninstall on the build servers. First, we need `dotnet workload install`, to assert the installation we need  `dotnet workload list` and so on
