### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#362]
Add test coverage for actually executing aliases against tools.

Currently there's no test coverage to ensure that the runners for each alias actually execute the target tool property. We should add a suite of tests that provide a framework for testing tool runners against live tools and verifying the results.

See https://github.com/cake-build/cake/issues/359 as an example.

**Comment by devlead** [comment]
What I would like would be if we ran the sample code, then we would test both that and integration.
I thought a little about it, only issue is the state setup/teardown, though would actually be kinda cool if the sample code had that when possible as would be a complete usage sample then.

**Comment by patriksvensson** [comment]
I would rather see dedicated, specialized integration tests initially. Sample code tests feels like something you build upon that.

**Comment by devlead** [comment]
Indeed integration test could test the sample code as one step. Basically we could extract all sample code into cake files in a integration tests repo automatically. Then that repo could bootstrap anything needed for sample code.

**Comment by patriksvensson** [comment]
Yes, sounds reasonable. I have a Powershell script lying around that runs some integrations tests. Maybe I should put some effort in this while I have some spare time... :smile:

**Comment by jrnail23** [comment]
@patriksvensson & @devlead, I'm working on further extending  `IProcess`'s functionality, but I'm a bit uncomfortable doing much without actual tests for the process wrapper itself.  
On one hand, that wrapper should ostensibly be thin enough to allow us to not worry too much (since it is really just a wrapper around otherwise untestable stuff), but on the other hand, there's already some stuff in there that deserves testing.

The reason I'm posting here is that it seems like one decent way to test this thing is by running a few *.cmd scripts via the Process mechanism  (Effectively an integration test rather than a unit test).
Since I don't see any existing code that does anything like this, I figured I'd run it by you guys before coming up with something myself.  

Should we create a separate integration test project for things like this, or perhaps just put it in the existing test project, under a different namespace with distinct categories for the tests?  Or would you guys prefer not to bother with this at all?

**Comment by devlead** [comment]
@jrnail23 integration tests is something we need, to keep the main repo clean, I'm personally leaning towards having a seperate repo with cake scripts that actually executes the code for as much as possible.
Then we could catch regressions like argument typos etc before release. Basically we could have this repo trigger on sucessfull build of the Cake repo and always pull down lates Cake from myget. This would raise the quality of the releases.

**Comment by patriksvensson** [comment]
@RichiCoder1 Took the liberty to update title of this issue since it's going to be included in the release notes :smile:

**Comment by gep13** [comment]
@patriksvensson @devlead do we need to create another issue, to track where we want integration tests added, similar to what we did with the documentation of the aliases?

**Comment by devlead** [comment]
@gep13 sounds reasonable. 👍
