### ISSUE TITLE
`Core` suffix is still used in some settings classes

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#3693]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

2.0.0-rc0001

### Operating system

N/A

### Operating system architecture

N/A

### What are you seeing?

All `DotNet` command settings, still have settings that have properties that contain the word `Core` in them.

For example:

`DotNetBuildSettings.MSBuildSettings` is of type `DotNet*Core*MSBuildSettings`
`DotNetBuildSettings.RollForward` is of type `DotNet*Core*RollForward?`
`DotNetBuildSettings.Verbosity` is of type `DotNet*Core*Verbosity?`

This goes for all `DotNet*Settings` related classes.

### What is expected?

That the `Core` suffix is removed.

### Steps to Reproduce

Se above

**Comment by devlead** [comment]
Is this fixed by https://github.com/cake-build/cake/issues/3683?

**Comment by augustoproiete** [comment]
> `DotNetBuildSettings.MSBuildSettings` is of type `DotNet*Core*MSBuildSettings`

This fixed by https://github.com/cake-build/cake/issues/3683

---

> `DotNetBuildSettings.RollForward` is of type `DotNet*Core*RollForward?`
> `DotNetBuildSettings.Verbosity` is of type `DotNet*Core*Verbosity?`

These are tricky ones because they are both enums in Cake v1.x and we can't use inheritance to keep backwards compatibility as we did with all the different settings classes. So `DotNetRollForward` is just syntactic sugar to allow you to use the new name (without the `Core`).

i.e. `DotNetRollForward.Major` is the same as `DotNetCoreRollForward.Major`

I'm sure it's possible to change, but I believe it will require updating the underlying runners that are called by the aliases (e.g. `DotNetCoreRunner`), and possibly add some "smart enum" implementation with implicit conversion, etc. to maintain backwards compatibility 🤔 . I'll do some tinkering.

---

I didn't find any other property in any of the new `DotNet***Settings` other than the above - let me know if I missed anything.

The only usage of `DotNetCore***` other than the above are the runners that are used by the aliases, and some settings classes that inherit `DotNetCore***Settings` for backwards compatibility with generic base classes like `ToolSetings<T>`, etc..
