### ISSUE TITLE
Copying a single file with no destination path, will not throw exceptions

### ISSUE THREAD

**Issue by ToMee99** [cake-build/cake#3720]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake runner for .NET Core

### Cake version

release 2.0.0-rc0002

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

When you don't create the destination folder and you pass destination path that does not exist, it will not throw an exception.

I created a test in FileCopierTests.cs:
`

         [Fact]
         public void Should_Throw_If_TargetDirectory_Does_Not_Exists_In_Copy_File()
         {

          const string filePath = "./src/a/a.txt";
          const string dstPath = "./dst";

          // Given
          var fixture = new FileCopierFixture();
          fixture.EnsureFileExists(filePath);

          // When
          var result = Record.Exception(() => FileCopier.CopyFile(fixture.Context, filePath, dstPath));

          AssertEx.IsExceptionWithMessage<DirectoryNotFoundException>(result, $"The directory '{dstPath}' does not exist.");
         }
`

When I run it, the test will fail, because the exception will not throw. 
I believe that the function `targetFilePath.GetDirectory().MakeAbsolute(context.Environment);` is assigning the destination path to the root folder. So that is why it not throwing any exception.

### What is expected?

The function `CopyFile` will throw an exception, when destination folder is not created.

### Steps to Reproduce

1. create a new dummy file for example : "./src/a/a.txt";`
2. copy file with function FileCopier.CopyFile(fixture.Context, filePath, dstPath));
3. where `dstPath` is a path to a folder that does not exist and `filePath` is a path to your dummy file.

### Output log

```
Message: 
    Assert.IsType() Failure
    Expected: System.IO.DirectoryNotFoundException
    Actual:   (null)
```

**Comment by devlead** [comment]
FileCopier CopyFile has the following signature 

CopyFile(ICakeContext context, FilePath filePath, FilePath targetFilePath) 

https://github.com/cake-build/cake/blob/926398d84d3aa9708aa26fc0532e070f904be152/src/Cake.Common/IO/FileCopier.cs#L35

So it's from one file path to another, in that case `./dst` should be a valid relative path.

FileCopier CopyFileToDirectory has a signature of CopyFileToDirectory(ICakeContext context, FilePath filePath, DirectoryPath targetDirectoryPath)

https://github.com/cake-build/cake/blob/926398d84d3aa9708aa26fc0532e070f904be152/src/Cake.Common/IO/FileCopier.cs#L18

**Comment by FrankRay78** [comment]
Hi @devlead, 

I recreated and tested the bug report above, and as suggested in your response, I believe it's working as documented.

When making the following call:

`CopyFile("./src/a/a.txt", "./dst");`

It completes successfully and with no exception thrown.

That's because a file called 'dst' is created (no extension), at the same level of the cake build script being run, and with the contents of 'a.txt'  As far as the method is concerned, the file is actually copied.

Executing the same but with the CopyFileToDirectory method, ie: 

`CopyFileToDirectory ("./src/a/a.txt", "./dst");`

Throws `Error: The directory '[snip]/dst' does not exist.` exception

So I see no reason why this issue shouldn't be closed (or similar).

**Comment by devlead** [comment]
@FrankRay78 excellent thanks.
