### ISSUE TITLE
DotNetCore -> DotNet Rename Missed Objects

### ISSUE THREAD

**Issue by BlythMeister** [cake-build/cake#3722]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool, Cake Frosting, Cake runner for .NET Framework, Cake runner for .NET Core

### Cake version

2.0.0-rcx

### Operating system

N/A

### Operating system architecture

N/A

### What are you seeing?

The new DotNetMSBuildSettings object (https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettings.cs) iteself references some `DotNetCore` namespaced classes.

### What is expected?

`DotNetCore` namespace is all obsolete and replaced with the `DotNet` namespace

### Steps to Reproduce

See file https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettings.cs it has a using statement `Cake.Common.Tools.DotNetCore.MSBuild;` as it neededs things in the `DotNetCore` namespace.

**Comment by augustoproiete** [comment]
Thanks @BlythMeister. This one you spotted is "_by design_".

The goal was to introduce the new `DotNet***` **aliases** without introducing breaking changes to existing `DotNetCore***` aliases.

Unfortunately the class `MSBuildLoggerSettings` which is in the old `...DotNetCore` namespace doesn't have the `Core` suffix on it, so I couldn't add it to the new `...DotNet` namespace and keep the old one at the same time as I did with all the other classes, because that causes ambiguity in Cake scripts as the compiler doesn't know which one to pick...

The plan is to remove all the `DotNetCore***` on Cake 3.0 ➡️  https://github.com/cake-build/cake/issues/3341 at which point the old `...DotNetCore` namespace will disapear.

That said, the fact that `MSBuildLoggerSettings` relies on the old namespace (in theory) should be an implementation detail and should not make any difference for the user in Cake scripts and with most Frosting builds...

The only scenario I can think of where you would still need to include the old namespace is Frosting-only, if you specifically use `MSBuildLoggerSettings` in your code.

Let me know if I missed anything

**Comment by BlythMeister** [comment]
Yeah, that's exactly how I noticed it, in my frosting project I bulk removed the "Core" from "DotNetCore" and this updated the using.

It's not something I'm too concerned about to be honest and the reasoning makes perfect sense.

So this can be closed 👍

**Comment by BlythMeister** [comment]
The only other potential idea could be to move the classes in cake 2.x.
And make the "DotNetCore" namespaced versions reference the objects in the new namespace?

At some point, this will be a hard break for someone using frosting whereby the namespace is in a using statement.

Is it better to make that hard break now so its when they are changing to the new alias?

**Comment by augustoproiete** [comment]
Is this what you mean?

1.) Copy `Cake.Common.Tools.DotNetCore.MSBuild.MSBuildLoggerSettings` to `Cake.Common.Tools.DotNet.MSBuild.MSBuildLoggerSettings`

2.) Rename `Cake.Common.Tools.DotNetCore.MSBuild.MSBuildLoggerSettings` to something like `Cake.Common.Tools.DotNetCore.MSBuild.MSBuildCoreLoggerSettings`

?

Therefore breaking Frosting now, rather than in 3.0?

**Comment by BlythMeister** [comment]
Yeah exactly (and any of the other classes in the DotNetCore namespace which don't have DotNetCore in the name.

I think it will mean 1 breaking release rather than 2.
For me, obsolete is breaking as our corporate environment has warnings as errors enabled 😂

**Comment by augustoproiete** [comment]
@BlythMeister Unfortunately we missed the boat on this one... Cake v2.0 shipped earlier today, so we'll have to schedule this one for v3.0

**Comment by arrowd** [comment]
Sorry if this is a wrong place to report, but I'm having issue related to this change when building GtkSharp:

```
 arrowd: ~/GtkSharp% ~/.dotnet/tools/dotnet-cake -v Diagnostic
Looking for modules...
No modules found to install.
Module directory does not exist.
Analyzing build script...
Analyzing /usr/home/arrowd/GtkSharp/build.cake...
Analyzing /usr/home/arrowd/GtkSharp/CakeScripts/GAssembly.cake...
Analyzing /usr/home/arrowd/GtkSharp/CakeScripts/Settings.cake...
Analyzing /usr/home/arrowd/GtkSharp/CakeScripts/TargetEnvironment.cake...
Processing build script...
Installing addins...
The addin Cake.FileHelpers will reference .cake/Addins/Cake.FileHelpers.5.0.0/lib/net6.0/Cake.FileHelpers.dll.
The addin Cake.Incubator will reference .cake/Addins/Cake.Incubator.7.0.0/lib/net6.0/Cake.Incubator.dll.
The addin Microsoft.Win32.Registry will reference .cake/Addins/Microsoft.Win32.Registry.5.0.0/lib/netstandard2.0/Microsoft.Win32.Registry.dll.
Verifying assembly 'Cake.FileHelpers, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
The assembly 'Cake.FileHelpers, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (2.0.0). 
For best compatibility it should target Cake.Core version 5.0.0.
Verifying assembly 'Cake.Incubator, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
The assembly 'Cake.Incubator, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (2.0.0). 
For best compatibility it should target Cake.Core version 5.0.0.
Verifying assembly 'Microsoft.Win32.Registry, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Error: System.TypeLoadException: Could not load type 'Cake.Common.Tools.DotNetCore.Test.DotNetCoreTestSettings' from assembly 'Cake.Common, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.<get_Signature>g__LazyCreateSignature|25_0()
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Cake.Core.Scripting.ScriptAliasFinder.GetAliasMethods(Type type)+MoveNext() in C:\projects\cake\src\Cake.Core\Scripting\ScriptAliasFinder.cs:line 154
   at Cake.Core.Scripting.ScriptAliasFinder.FindAliases(IEnumerable`1 assemblies) in C:\projects\cake\src\Cake.Core\Scripting\ScriptAliasFinder.cs:line 46
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 145
   at Cake.Features.Building.BuildFeature.RunCore(ICakeArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 99
   at Cake.Features.Building.BuildFeature.Run(ICakeArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 49
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings) in C:\projects\cake\src\Cake\Commands\DefaultCommand.cs:line 77
```
