### ISSUE TITLE
Line number in error messages is incorrect when using directives

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#375]
When using directives, e.g. _#r_ or _#load_ in a cake script,  the line numbers in syntax error messages are wrong. I have to add the number of directive lines to it to get the correct one...

**Comment by jrnail23** [comment]
interesting... perhaps it would be possible to have the scripting engine retain those directive lines as comments?

**Comment by devlead** [comment]
As it's combined into one code generated script, we would need to keep track of offsets or something.

**Comment by RichiCoder1** [comment]
I've been getting around this using `#line` directives, but it would be nice to have Cake handle this out of the box.

**Comment by patriksvensson** [comment]
If I understand correctly, I think that @jrnail23 s solution is the best one. The reason for our inserted `#line` directives to be wrong is because we remove other directives after processing them. By readding them to the script as comments, we both get something that's easier to debug (when we're debugging Cake) and we make sure that the line numbers are correct.
