### ISSUE TITLE
Easier Way to Read Process Output?

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#3947]
### Discussed in https://github.com/orgs/cake-build/discussions/3837

<div type='discussions-op-text'>

<sup>Originally posted by **RehanSaeed** March 10, 2022</sup>
I'm executing a process and reading the output like so:

```cs
StartProcess(
    "az",
    new ProcessSettings()
        .WithArguments(x => x
            .Append("account")
            .Append("list-locations"))
        .SetRedirectStandardOutput(true),
        out var lines);
var json = string.Join(Environment.NewLine, lines);
```

This is pretty cumbersome. I'd really like something far simpler like [simple-exec](https://github.com/adamralph/simple-exec) built into Cake build aliases so I don't have to include yet another dependency:

```cs
var (standardOutput, standardError) = await ReadAsync("az account list-locations");
```

I don't believe anything like this currently exists unless there is an alias I'm missing?</div>

**Comment by Jericho** [comment]
@devlead Thanks for this improvement. I'm in the process of removing `StartProcess` from my Cake scripts and replacing them with the new `Command`. One thing I struggled with is how to specify the tool to execute without using the built-in tool resolution. In other words, I know precisely the location of my desired tool, and I would like to be able to simply specify the full path. 

I came up with the following solution, but it feels very verbose to be forced to specify the tool name, tool executable names and tool path:
```csharp
Command(
	new CommandSettings
	{
		ToolName = appName,
		ToolExecutableNames = new[] { appName, $"{appName}.exe" },
		ToolPath = $"{publishDir}{appName}.exe",
	},
	new ProcessArgumentBuilder()
		.Append("nopause")
);
```
I tried specifying `ToolPath` only, but I get "Null" exceptions due to the fact that I omitted ToolName and ToolExecutableNames. Therefore, I am forced to specify all three properties.

It would be great to be able to only specify the `FilePath` of the desired tool. Something along these lines:
```csharp
Command(
	new FilePath($"{publishDir}{appName}.exe"),
	new ProcessArgumentBuilder()
		.Append("nopause")
);
```

**Comment by devlead** [comment]
@Jericho If ToolPath specified we should be able to use it. So that could be a potential improvement.

For now you should, instead of specifying ToolPath be able to register your exes fullpath with Cake tools resolution, that way tool resolution will find it.

```cake 
Context.Tools.RegisterFile("C:/ProgramData/chocolatey/bin/NuGet.exe")
```

https://cakebuild.net/docs/writing-builds/tools/tool-resolution

**Comment by Jericho** [comment]
> If ToolPath specified we should be able to use it

That would indeed be the best option (in my humble opinion!).
