### ISSUE TITLE
Allow use of ICakeContext in WithCriteria 

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#512]
Overload `CakeTaskBuilder.WithCriteria` to accept `Func<ICakeContext,bool> `.
I'm factoring out some common behaviors in my scripts into reusable tasks, but not having the context available in `WithCriteria` is causing some friction.

Anyone have a reason that context shouldn't be allowed there?

**Comment by patriksvensson** [comment]
Sounds like a reasonable addition. Will make the task API more consistent as well :+1:

**Comment by ErikSchierboom** [comment]
I am looking into this, and was wondering how I should add it to the existing `CakeTask` class. This class has a property that contains all existing boolean criterias: `public IReadOnlyList<Func<bool>> Criterias`. In the `ShouldTaskExecute` method in the `CakeEngine` class, the aforementioned `Criterias` property is iterated over. Should I create an additional property which signature is like this: `public IReadOnlyList<Func<ICakeContext, bool>> ContextCriterias`? Or should `Func<bool>` instances be converted to `Func<ICakeContext, bool>` instances and the existing `Criterias` property thus return `IReadOnlyList<Func<ICakeContext, bool>>`?

**Comment by patriksvensson** [comment]
@ErikSchierboom I would prefer if we changed `CakeTask.Criterias` to be a `IReadOnlyList<Func<ICakeContext, bool>>` and converted the `Func<bool>` to a `Func<ICakeContext, bool>`.

We could also make the `void AddCriteria(Func<bool> criteria)` an extension method (since it's more or less a convenience method) and change the implementation in `CakeTask` to `void AddCriteria(Func<ICakeContext, bool> criteria)`

**Comment by patriksvensson** [comment]
Merged via #663.
