### ISSUE TITLE
Support custom environment for tool (e.g. NUnit3)

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#653]
Is there a possibility to change the environment for a tool which is started from Cake?
I can think of creating a custom TEMP directory for NUnit which is deleted after the test run...
I did not find anything to modify the environment in the ```ToolSettings``` class

**Comment by patriksvensson** [comment]
Hello @Sam13,

I'm not sure that I follow what you mean here. 
Could you elaborate on this? What do you mean by environment?

**Comment by Sam13** [comment]
I'd like to override the environment variables for the new tool process, e.g. to redirect the TEMP path. 
see https://msdn.microsoft.com/de-de/library/system.diagnostics.processstartinfo.environmentvariables%28v=vs.110%29.aspx

**Comment by patriksvensson** [comment]
@Sam13 We currently have no support for this in Cake, but I guess that a solution could be to allowing registration of environment variables in the `ToolSetting` and set them in [System.Diagnostics.ProcessStartInfo.Environmentvariables](https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.environmentvariables(v=vs.110).aspx). We would however need to change `UseShellExecute` to true to make this work, so this is a big change and should be discussed properly since we don't want to introduce any side effects.

A workaround would be if you built your own functionality to start NUnit until we've sorted this out.

**Comment by Sam13** [comment]
@patriksvensson I think it would be a cool feature to allow this in Cake since this was even possible with NAnt ;-)

**Comment by dsparkplug** [comment]
@patriksvensson Please note that UseShellExecute needs to be **false** (so no change) when set environment variables via [ProcessStartInfo.EnvironmentVariables](https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.environmentvariables(v=vs.110).aspx)

**Comment by patriksvensson** [comment]
@dsparkplug You are correct. Thanks :smile:

**Comment by Sam13** [comment]
Good news, so maybe we can add the working directory for custom tool as well?

**Comment by patriksvensson** [comment]
@Sam13 We shoule open a new issue for the working directory stuff.

**Comment by devlead** [comment]
Addressed by #1094 and #661
