### ISSUE TITLE
gulp is not invoked when building a solution using cake

### ISSUE THREAD

**Issue by mbischoff** [cake-build/cake#672]
The attached sample solution contains an ASP.NET project, where a gulp task is bound to the BeforeBuild event. When building the solution inside Visual Studio, the gulp task is executed (`css/style.less` is compiled to `css/style.css`).

When I use cake to build the project, the gulp task is not executed (tried with both `DotNetBuild()` and `MSBuild()` tasks).

See also: [http://stackoverflow.com/questions/35177555/can-i-invoke-gulp-from-a-cake-build-file](http://stackoverflow.com/questions/35177555/can-i-invoke-gulp-from-a-cake-build-file)

[WebApplication1.zip](https://github.com/cake-build/cake/files/117117/WebApplication1).

**Comment by devlead** [comment]
Just did a quick look so I might be missing something but checking the csproj the before build MSBuild seems empty?
```xml
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
```
![WebApplication1 Build Events](https://cloud.githubusercontent.com/assets/1647294/12812011/627bba52-cb30-11e5-819a-a2edf58923f4.png)

Visual Studio 2015 has a built-in task runner for gulp/grunt so might be that's what kicking in.

Currently we don't, have aliases for npm or gulp yet(that would be an great addin though), but what you could do is invoke gulp your self via `StartProcess` alias, I tweaked your `build.cake` slighly below:
```cake
var target = Argument("target", "Default");
DirectoryPath   solutionDir = MakeAbsolute(Directory("./"));
FilePath        solution    = solutionDir.CombineWithFilePath("WebApplication1.sln");
DirectoryPath   projectDir  = solutionDir.Combine("WebApplication1");
FilePath        lessOutput  = projectDir.CombineWithFilePath("css/style.css");

Task("Default")
  .Does(() =>
{
  NuGetRestore(solution);

  if (FileExists(lessOutput))
  {
    Information("Cleaning old less output {0}", lessOutput);
    DeleteFile(lessOutput);
  }

  StartProcess("cmd", new ProcessSettings {
        Arguments        = "/c \"set CI=true && npm install && gulp compile-less\"",
        WorkingDirectory = projectDir
    });

  if (!FileExists(lessOutput))
  {
    throw new Exception("Less failed to create " + lessOutput);
  }
  Information("Less created {0}", lessOutput);

  MSBuild(solution);
});

RunTarget(target);
```

This assumes you have node & gulp installed globally (you install gulp globally via running `npm install -g gulp`), also this was 5 min quick n dirty, so you would want to divide clean/restore/less into separate cake tasks. I set environment CI=true because some node modules could require user interaction on restore otherwise.

Discarding MSBuild / nuget restror above will output something like
```
Cleaning old less output C:/temp/cake_issue_672/WebApplication1/WebApplication1/css/style.css
[11:26:12] Using gulpfile C:\temp\cake_issue_672\WebApplication1\WebApplication1\gulpfile.js
[11:26:12] Starting 'compile-less'...
[11:26:13] Finished 'compile-less' after 29 ms
Less created C:/temp/cake_issue_672/WebApplication1/WebApplication1/css/style.css
```

This might not be the solution you were working for, but it _"should"_ work :wink:

**Comment by gep13** [comment]
@mbischoff I just wanted to check something...

Are you referring to this:

![image](https://cloud.githubusercontent.com/assets/1271146/12813191/5d8282c6-cb2e-11e5-8efa-bc4a14b020e0.png)

i.e. the Task Runner Explorer Extension for Visual Studio that Mads created?

**Comment by mbischoff** [comment]
@gep13 : yes that's what I'm using to configure when the gulp tasks should be run. AFAIK this comes standard with VS2015 (not a separate extension).

The gulp tasks are bound to the BeforeBuild event via the first line (comment) in gulpfile.js:

`/// <binding BeforeBuild='compile-less' ProjectOpened='watch' />`

**Comment by patriksvensson** [comment]
@mbischoff My guess is that this is invoked via a VS extension bundled with Visual Studio and is not invoked via a custom MSBuild target.

**Comment by mbischoff** [comment]
@devlead : that might be a workaround then. I'll try it later.

**Comment by mbischoff** [comment]
@patriksvensson yes seems so. I thought that the whole task runner stuff (gulp, grunt, etc) was the new "standard" way to do such things (replacing the previous "Web Essentials" extension). And I therefore thought that it would be better integrated.

**Comment by gep13** [comment]
@mbischoff it may come pre-bundled with Visual Studio when you install it, but it is an extension in it's own right:

![image](https://cloud.githubusercontent.com/assets/1271146/12815409/239545d4-cb3e-11e5-8af6-ddb7e1c54ef9.png)

It is integrated as well as it can be just now, without entirely ripping out MSBuild and starting again,

**Comment by devlead** [comment]
@gep13 @patriksvensson @mbischoff it's like that by design as it runs in parallell with the IDE, i.e. gulp watch mode so you'll get you changes as soon as you change any file. 
VS will also automagicially restore node modules on open, something you'll also need to cater yourself in build / deploy scripts.

**Comment by devlead** [comment]
@mbischoff great try it and let us now if the way I supplied works for you or not.

**Comment by devlead** [comment]
@mbischoff have you had any chance to test? Is the issue resolved?

**Comment by mbischoff** [comment]
@devlead : it worked a few times. As you wrote, node and gulp have to be installed first.

But even then, most of the times I had problems executing gulp from the cakebuild (got error "gulp is not recognized as an internal or external command, operable program or batch file"). At the moment I'm unable to find out what I did differently when it worked.

I'm giving up for the moment, but will retry once I have more time.

As this is not a problem or bug in cake-build, I'm closing the issue.

**Comment by devlead** [comment]
@mbischoff ok, this would indicate gulp not in path.

You could try specifying exact path, i.e. if installed globally it usually in some place like
`C:\Users\[user]\AppData\Roaming\npm\gulp.cmd` 
on windows.

You can also run this in a shell prompt to get exact path
`cmd /c where gulp`

If you have node in path you can basically launch gulp with absolute paths i.e. something like
`"C:\Program Files\nodejs\node.exe" "C:\Users\[user]\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js"`
