### ISSUE TITLE
Support for SHA256 code signing

### ISSUE THREAD

**Issue by tonyedgecombe** [cake-build/cake#685]
As of 1st January Microsoft [no longer accepts SHA1 certificates](http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx) for code signing.

The existing Sign code does not support SHA256 signing and timestamps.

The required options are:

```
/fd File digest algorithm
/tr RFC 3161 compatible time stamp server
/td Timestamp digest algorithm
/as Append signature (to enable signing for XP and Vista) 
```

**Comment by swanitzek** [comment]
I have the same problem.

Even appening the required argument via the ArgumentBuilder isn't possible because the order of the arguments passed to signtool matters.

A valid command line for signing a file with SHA256 looks like this:

`signtool.exe SIGN /sha1 "<THUMBPRINT>" /fd sha256 "File.exe"`

A possible workaround is to prepare the correct argument string manually and call signtool.exe directly.

**Comment by patriksvensson** [comment]
@swanitzek You can slso return a new ProcessArgumentBuilder from the ArgumentCustomization lambda and rewrite all parameters that way.

**Comment by mholo65** [comment]
@patriksvensson, mind if I take a stab on this one? Needed to sign using sha256 today, and doing the ArgumentCustomization dance was a ugly workaround.

**Comment by devlead** [comment]
@mholo65 Perfect I've assigned this issue to you.

**Comment by gep13** [comment]
Big thanks to @mholo65 for implementing this!
