### ISSUE TITLE
Loading cake scripts from nuget packages.

### ISSUE THREAD

**Issue by zhech2** [cake-build/cake#843]
In reading the following post:
https://github.com/cake-build/cake/issues/82

I saw the following comments by patriksvensson and it looks like something I would like to use.

```
// Reference a specific script in a NuGet package.
#nuget -script "MyCoolNugetPackage.Scripts", "CoolStuff.cake"

// Reference all scripts that matches the globbing pattern.
#nuget -scripts "MyCoolNugetPackage.Scripts", "**\*.cake"
```

Maybe it could be defined as follows:
```
// could use #tool or #addin
#tool nuget:http://myget.org/feed/?package=example -scripts "**\*.cake"  
// reference cake files in nuget package
::load tools/example/setup.cake         
// project specific cake files
::load project.setup.cake                    
```

This would allow for getting a nuget package and import the scripts from the package all at the same time without the need for creating a bootstrapper.

Is this something you would be willing to add to cake?  I would be willing to implement or help implement.

**Comment by patriksvensson** [comment]
@zhech2 This is something that we currently have postponed in our roadmap since it would require us to rewrite large portions of the source code.

To be able to integrate with tools like Omnisharp in the future we have divided the script processing in two phases; analysis (gathers information about all scripts, their content and addins/tools) and a processing phase that installs addins and tools and stitches together the final script. This allows us to gather information quickly about scripts without reaching out to nuget and similar. A change like this would require us to make script processing recursive (since a script in a package can require more scripts/addins/tools). We currently do not want to do this since it would add even more magic to how Cake scripts work.

I would say that a better approach (at the moment) would be to download the script packages in your bootstrapper and reference the scripts in the package directly from your cake scripts.
