### ISSUE TITLE
Remove obsoleted XmlPoke aliases

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#978]
As discussed in #974 it's now time to remove the obsoleted XmlPoke aliases.

**Comment by gep13** [comment]
@devlead If you want the `Breaking Change` label to appear in the release notes, which i think is a good idea, we will need to add the label to the GitReleaseManager.yaml file, so that it picks it up.

**Comment by devlead** [comment]
@gep13 agree, should I send a separate pr/issue there?

**Comment by gep13** [comment]
@devlead yes, I think that would be justified, yes.

**Comment by devlead** [comment]
@gep13  cool, I'll fix that shortly.

**Comment by devlead** [comment]
@gep13 #979 should be ready for review as is then.

**Comment by gep13** [comment]
@devlead I think it was mentioned elsewhere as well, but just to recap...  I think we need a new page on the website that lists when Aliases were obsoleted, i.e. in what version of Cake. And we can keep a track of things there, so that we can point people to.

i.e. when method was added, when it was obsoleted, and when it was removed.

Thoughts?

**Comment by patriksvensson** [comment]
@gep13 @devlead Yes, I think this is a good idea. Actually, we could create our own `ObsoleteAttribute` as well with this information and generate it from the NuGet package.

**Comment by devlead** [comment]
We could use something like Particular Software API comparer to diff public APIs between versions.

**Comment by ravensorb** [comment]
Disappointed that this has been removed -- I have been using it to update NuSpec details since your default NuSpec aliases overwrite the entire file rather than update only specific parts.  Please bring it back.
